In [2]:
import csv
import numpy as np 
from numpy import zeros, pi, sin, cos, sqrt

In [ ]:


# Build long chain of carbons along z-axis

def carbonchain(natoms):

# Bond angle and bond lengths  
    #natoms = 30
    atom_list = ['C']*natoms
    Ccov_r = 0.77
    ccbond = 2*Ccov_r

# Carbons coordinates in x-direction
    xcoord = [0]*natoms
    dx = np.array(xcoord)
    #print(dx.shape)

# Carbons coordinates in y-direction
    ycoord = [0]*natoms 
    dy = np.array(ycoord)
    #print(dy.shape)

# Carbons coordinates in z-direction    
    zcoord = []
    num = 0       
   
    while num <= (ccbond*natoms): 
        num += ccbond 
        zcoord.append(num)
    del zcoord[-1]
    dz = np.array(zcoord)
    #print(dz.shape)  
    
    coord = np.dstack((dx, dy, dz))
    print(coord)

### Saving data as arrays into an .xyz file
    with open('carbon_chain.xyz','w') as f:
        writer = csv.writer(f, delimiter='\t')
        writer.writerows(zip(atom_list, dx, dy, dz))
    
   
    
    return(coord)

print(carbonchain(30))
        
    

In [34]:
def add_Hatoms(C_atoms):
    
    atom_list = ['H']*C_atoms*2
    Ccov_r = 0.77
    Hcov_r = 0.32
    chbond = Ccov_r + Hcov_r
       

# Coordinates for each hydrogen
    numz = chbond*cos(109.5/2*(pi/180))
    numy1 = (chbond*sin((109.5/2*pi/180)))
    numy2 = (-chbond*sin((109.5/2*pi/180)))
    
# Setting x-coordinates 
    xcoord = [0]*C_atoms*2
    dx = np.array(xcoord)
#print(dx.shape)

# Setting y-coordinates
    ycoord_H1 = [numy1]*(C_atoms)
    ycoord_H2 = [numy2]*(C_atoms)
    ycoord = ycoord_H1 + ycoord_H2
    dy = np.array(ycoord)
#print(dy.shape)

# Setting z-coordinates
    zcoord1 = [] 
    zcoord2 = []
    hatom = 0

    while hatom <= (numz*C_atoms): 
        hatom += numz
        zcoord1.append(hatom)
        zcoord2.append(hatom)
## Make the arrays the same size

    del zcoord1[-1]
    del zcoord2[-1]

    dz = np.array(zcoord1+zcoord2)
    print(dz.shape)


    coord = np.dstack((dx, dy, dz))

   
### Saving data as arrays into an .xyz file
    with open('carbon_chain.xyz','a') as f:
        writer = csv.writer(f, delimiter='\t')
        writer.writerows(zip(atom_list, dx, dy, dz))

    return(coord)
print(add_Hatoms(30))

(60,)
[[[ 0.          0.8901393   0.62908826]
  [ 0.          0.8901393   1.25817651]
  [ 0.          0.8901393   1.88726477]
  [ 0.          0.8901393   2.51635303]
  [ 0.          0.8901393   3.14544129]
  [ 0.          0.8901393   3.77452954]
  [ 0.          0.8901393   4.4036178 ]
  [ 0.          0.8901393   5.03270606]
  [ 0.          0.8901393   5.66179431]
  [ 0.          0.8901393   6.29088257]
  [ 0.          0.8901393   6.91997083]
  [ 0.          0.8901393   7.54905909]
  [ 0.          0.8901393   8.17814734]
  [ 0.          0.8901393   8.8072356 ]
  [ 0.          0.8901393   9.43632386]
  [ 0.          0.8901393  10.06541211]
  [ 0.          0.8901393  10.69450037]
  [ 0.          0.8901393  11.32358863]
  [ 0.          0.8901393  11.95267689]
  [ 0.          0.8901393  12.58176514]
  [ 0.          0.8901393  13.2108534 ]
  [ 0.          0.8901393  13.83994166]
  [ 0.          0.8901393  14.46902991]
  [ 0.          0.8901393  15.09811817]
  [ 0.          0.8901393  15.7272

In [52]:
def add_OH(natoms, n_OH, n_HO):

#Number of oxygens in number of OH groups = n_OH 
#Number of hydrogens in number of OH groups = n_HO 
#natoms = 30

    atom_list = ['OH']*(n_OH + n_HO)
    Hcov_r = 0.32
    Ocov_r = 0.66
    Ccov_r = 0.77
    cobond = Ccov_r + Ocov_r
    ohbond = Hcov_r + Ocov_r
    ccbond = 2*Ccov_r


# Oxygen coordinates in x-direction
    O_xcoord = [0]*n_OH
    O_dx = np.array(O_xcoord)

# Oxygen coordinates in y-direction
    O_ycoord = [0]*n_OH
    O_dy = np.array(O_ycoord)

# Oxygen coordinates in z-direction    
    O_zcoord = []
    O_zcoords = []
    num = 0       
    while num <= (ccbond*natoms): 
        num += ccbond 
        O_zcoord.append(num)
    del O_zcoord[-1]
    O_zcoord1 = O_zcoord[-1] + cobond
    O_zcoords.append(O_zcoord1)
    O_dz = np.array(O_zcoords)
    

    O_coord = np.dstack((O_dx, O_dy, O_dz))
    
        
# Hydrogen coordinates in x-direction
    H_xcoord = [0]*n_HO
    H_dx = np.array(H_xcoord)
    #print(dx.shape)

# Hydrogens coordinates in y-direction
    H_ycoord = []
    H_y = ohbond*cos((180-108.87)*pi/180)
    H_ycoord.append(H_y)
    H_dy = np.array(H_ycoord)
    #print(dy.shape)

# Hydrogen coordinates in z-direction    
    H_zcoord = []
    H_z = ohbond*sin((180-108.87)*pi/180)
    H_zcoord.append(H_z)
    H_dz = np.array(H_zcoord)


    H_coord = np.dstack((H_dx, H_dy, H_dz))


    with open('carbon_chain.xyz','a') as f:
        writer = csv.writer(f, delimiter='\t')
        writer.writerows(zip(atom_list, H_dx, H_dy, H_dz))
        writer.writerows(zip(atom_list, O_dx, O_dy, O_dz))
        
    return(O_coord, H_coord)
print(add_OH(30, 1, 1))

(array([[[ 0.  ,  0.  , 47.63]]]), array([[[0.        , 0.31695356, 0.92732974]]]))


(1,)
(1,)
[0] [0.31695356] [0.92732974]
[0] [0] [47.63]
